/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { ToDoTask } from "./ToDoTask";
import { ToDoTaskCountArgs } from "./ToDoTaskCountArgs";
import { ToDoTaskFindManyArgs } from "./ToDoTaskFindManyArgs";
import { ToDoTaskFindUniqueArgs } from "./ToDoTaskFindUniqueArgs";
import { CreateToDoTaskArgs } from "./CreateToDoTaskArgs";
import { UpdateToDoTaskArgs } from "./UpdateToDoTaskArgs";
import { DeleteToDoTaskArgs } from "./DeleteToDoTaskArgs";
import { ToDoUserFindManyArgs } from "../../toDoUser/base/ToDoUserFindManyArgs";
import { ToDoUser } from "../../toDoUser/base/ToDoUser";
import { User } from "../../user/base/User";
import { ToDoTaskService } from "../toDoTask.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ToDoTask)
export class ToDoTaskResolverBase {
  constructor(
    protected readonly service: ToDoTaskService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ToDoTask",
    action: "read",
    possession: "any",
  })
  async _toDoTasksMeta(
    @graphql.Args() args: ToDoTaskCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ToDoTask])
  @nestAccessControl.UseRoles({
    resource: "ToDoTask",
    action: "read",
    possession: "any",
  })
  async toDoTasks(
    @graphql.Args() args: ToDoTaskFindManyArgs
  ): Promise<ToDoTask[]> {
    return this.service.toDoTasks(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ToDoTask, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ToDoTask",
    action: "read",
    possession: "own",
  })
  async toDoTask(
    @graphql.Args() args: ToDoTaskFindUniqueArgs
  ): Promise<ToDoTask | null> {
    const result = await this.service.toDoTask(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ToDoTask)
  @nestAccessControl.UseRoles({
    resource: "ToDoTask",
    action: "create",
    possession: "any",
  })
  async createToDoTask(
    @graphql.Args() args: CreateToDoTaskArgs
  ): Promise<ToDoTask> {
    return await this.service.createToDoTask({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ToDoTask)
  @nestAccessControl.UseRoles({
    resource: "ToDoTask",
    action: "update",
    possession: "any",
  })
  async updateToDoTask(
    @graphql.Args() args: UpdateToDoTaskArgs
  ): Promise<ToDoTask | null> {
    try {
      return await this.service.updateToDoTask({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ToDoTask)
  @nestAccessControl.UseRoles({
    resource: "ToDoTask",
    action: "delete",
    possession: "any",
  })
  async deleteToDoTask(
    @graphql.Args() args: DeleteToDoTaskArgs
  ): Promise<ToDoTask | null> {
    try {
      return await this.service.deleteToDoTask(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [ToDoUser], { name: "todouser" })
  @nestAccessControl.UseRoles({
    resource: "ToDoUser",
    action: "read",
    possession: "any",
  })
  async findTodouser(
    @graphql.Parent() parent: ToDoTask,
    @graphql.Args() args: ToDoUserFindManyArgs
  ): Promise<ToDoUser[]> {
    const results = await this.service.findTodouser(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: ToDoTask): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
